{
  "steps": [
    {
      "name": "gcr.io/cloud-builders/docker",
      "args": [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/tokenhunter-457310/token-nav-repo/enhanced-multi-region-extractor:v2",
        "-f",
        "production/services/Dockerfile.enhanced-multi-region",
        "."
      ]
    },
    {
      "name": "gcr.io/cloud-builders/docker",
      "args": [
        "push",
        "us-central1-docker.pkg.dev/tokenhunter-457310/token-nav-repo/enhanced-multi-region-extractor:v2"
      ]
    },
    {
      "name": "gcr.io/google.com/cloudsdktool/cloud-sdk",
      "entrypoint": "gcloud",
      "args": [
        "run",
        "deploy",
        "enhanced-multi-region-us-central",
        "--image",
        "us-central1-docker.pkg.dev/tokenhunter-457310/token-nav-repo/enhanced-multi-region-extractor:v2",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--memory",
        "4Gi",
        "--cpu",
        "2",
        "--timeout",
        "1800",
        "--set-env-vars",
        "REGION=us-central1,COST_TIER=2"
      ]
    },
    {
      "name": "gcr.io/google.com/cloudsdktool/cloud-sdk",
      "entrypoint": "gcloud",
      "args": [
        "run",
        "deploy",
        "enhanced-multi-region-europe-west",
        "--image",
        "us-central1-docker.pkg.dev/tokenhunter-457310/token-nav-repo/enhanced-multi-region-extractor:v2",
        "--region",
        "europe-west1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--memory",
        "4Gi",
        "--cpu",
        "2",
        "--timeout",
        "1800",
        "--set-env-vars",
        "REGION=europe-west1,COST_TIER=3"
      ]
    }
  ],
  "options": {
    "logging": "CLOUD_LOGGING_ONLY",
    "machineType": "E2_HIGHCPU_8"
  },
  "timeout": "2400s"
}