# Enterprise Production Orchestrator Deployment
# Follows Nuru AI Enterprise Deployment Standards
# Priority: 01 = Primary deployment method

steps:
  # Build the container image from project root context
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/tokenhunter-457310/token-nav-repo/production-orchestrator:latest',
      '-t', 'us-central1-docker.pkg.dev/tokenhunter-457310/token-nav-repo/production-orchestrator:$BUILD_ID',
      '-f', 'src/extraction/deployment/Dockerfile',
      '.'
    ]
    dir: '.'

  # Push the latest image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'us-central1-docker.pkg.dev/tokenhunter-457310/token-nav-repo/production-orchestrator:latest'
    ]

  # Push the build-specific image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'us-central1-docker.pkg.dev/tokenhunter-457310/token-nav-repo/production-orchestrator:$BUILD_ID'
    ]

  # Deploy to Cloud Run with enterprise-grade settings
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'production-orchestrator',
      '--image', 'us-central1-docker.pkg.dev/tokenhunter-457310/token-nav-repo/production-orchestrator:latest',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '4Gi',
      '--cpu', '2',
      '--timeout', '3600',
      '--concurrency', '10',
      '--min-instances', '1',
      '--max-instances', '5',
      '--set-env-vars', 'DEPLOYMENT_TYPE=ENTERPRISE,BUILD_ID=$BUILD_ID'
    ]

# Enterprise Cloud Build configuration
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  sourceProvenanceHash: ['SHA256']

# Extended timeout for enterprise builds
timeout: '1800s'

# Images to be pushed to Artifact Registry
images:
  - 'us-central1-docker.pkg.dev/tokenhunter-457310/token-nav-repo/production-orchestrator:latest'
  - 'us-central1-docker.pkg.dev/tokenhunter-457310/token-nav-repo/production-orchestrator:$BUILD_ID'

# Enterprise metadata
substitutions:
  _SERVICE_NAME: 'production-orchestrator'
  _DEPLOYMENT_TIER: 'ENTERPRISE'
  _BUILD_ENV: 'PRODUCTION'