steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/tokenhunter-457310/token-nav-repo/enhanced-multi-region-extractor:v3'
      - '-f'
      - 'Dockerfile.enhanced-multi-region'
      - '.'
    dir: 'src/api'

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/tokenhunter-457310/token-nav-repo/enhanced-multi-region-extractor:v3'

  # Deploy to US Central region
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'enhanced-multi-region-us-central'
      - '--image'
      - 'us-central1-docker.pkg.dev/tokenhunter-457310/token-nav-repo/enhanced-multi-region-extractor:v3'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '1800'
      - '--max-instances'
      - '3'
      - '--min-instances'
      - '0'
      - '--concurrency'
      - '10'
      - '--set-env-vars'
      - 'REGION=us-central1,COST_TIER=2'

  # Deploy to Europe West region  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'enhanced-multi-region-europe-west'
      - '--image'
      - 'us-central1-docker.pkg.dev/tokenhunter-457310/token-nav-repo/enhanced-multi-region-extractor:v3'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '1800'
      - '--max-instances'
      - '3'
      - '--min-instances'
      - '0'
      - '--concurrency'
      - '10'
      - '--set-env-vars'
      - 'REGION=europe-west1,COST_TIER=3'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: 'CLOUD_LOGGING_ONLY'
timeout: '2400s'