---
# Documentation Generation Configuration for Othentic AVS Integration
documentation_generation:
  # Planning documents to use as source
  planning_documents:
    - "/Users/eladm/Projects/token/tokenhunter/docs/architecture/blockchain/OTHENTIC_AVS_ARCHITECTURE_PLAN.md"
    - "/Users/eladm/Projects/token/tokenhunter/docs/architecture/blockchain/MASUMI_INDEPENDENCE_STRATEGY.md"
    - "/Users/eladm/Projects/token/tokenhunter/docs/architecture/blockchain/MULTI_CHAIN_PAYMENT_ARCHITECTURE.md"
  
  # Target documentation structure
  target_structure:
    docs_root: "agent_forge/docs"
    
    # New directories to create
    new_directories:
      - "blockchain"
      - "payments" 
      - "compliance"
      - "deployment"
    
    # Target files to generate
    target_files:
      blockchain:
        - "README.md"
        - "OTHENTIC_AVS_ARCHITECTURE.md"
        - "MULTI_CHAIN_DEPLOYMENT.md"
        - "SMART_CONTRACT_PATTERNS.md"
        - "MIGRATION_GUIDE.md"
      
      payments:
        - "README.md"
        - "UNIVERSAL_ROUTER_GUIDE.md"
        - "CRYPTO_PROVIDERS.md"
        - "TRADITIONAL_FINANCE.md"
        - "ENTERPRISE_BANKING.md"
        - "PAYMENT_TESTING.md"
      
      compliance:
        - "README.md"
        - "REGKYC_INTEGRATION.md"
        - "ENTERPRISE_REQUIREMENTS.md"
        - "REGULATORY_REPORTING.md"
        - "AUDIT_TRAILS.md"
      
      deployment:
        - "README.md"
        - "OTHENTIC_DEPLOYMENT.md"
        - "PRODUCTION_CHECKLIST.md"
        - "MONITORING_SETUP.md"
  
  # AI model configuration
  ai_model: "gemini-2.5"
  
  # Generation settings
  settings:
    dry_run: false
    create_backups: true
    validate_consistency: true
    generate_index_files: true
    
  # Quality requirements
  quality_requirements:
    minimum_quality_score: 0.8
    require_all_sections: true
    enforce_terminology: true
    validate_cross_references: true
  
  # Template customization
  template_overrides:
    header_format: |
      # {title}
      
      **Version:** {version}  
      **Date:** {date}  
      **Status:** {status}  
      **Component:** Agent Forge Othentic AVS Integration  
    
    footer_format: |
      ---
      
      **Last Updated:** {date} - {update_summary}  
      **Generated by:** Documentation Manager Agent  
      **Related:** [Agent Forge Documentation](../README.md)

# Consistency rules
consistency:
  terminology:
    "Agent Forge": "Agent Forge"
    "Othentic AVS": "Othentic AVS"  
    "Masumi Network": "Masumi Network"
    "NMKR": "NMKR"
    "proof-of-execution": "Proof-of-Execution"
    "multi-chain": "multi-chain"
    "payment provider": "payment provider"
  
  formatting:
    date_format: "%B %d, %Y"
    version_format: "1.0"
    status_options: ["Active Development", "Planning", "Complete", "Deprecated"]
    code_language: "python"
  
  structure:
    required_sections:
      - "Overview"
      - "Architecture" 
      - "Implementation"
      - "Testing"
    max_section_depth: 3
    require_examples: true

# Validation rules
validation:
  file_checks:
    - check_file_exists
    - validate_markdown_syntax
    - verify_internal_links
    - check_code_blocks
  
  content_checks:
    - terminology_consistency
    - section_completeness
    - example_validity
    - cross_reference_accuracy
  
  quality_gates:
    minimum_content_length: 1000
    maximum_placeholder_count: 0
    required_code_examples: 2
    minimum_sections: 4