# =============================================================================
# SERVICE ACCOUNT MANAGEMENT CONFIGURATION
# Enterprise Configuration Management - Phase 2 Enhancement
# =============================================================================

project_id: "tokenhunter-457310"

# Primary service accounts
service_accounts:
  api_service:
    email: "chatbot-api-sa@tokenhunter-457310.iam.gserviceaccount.com"
    display_name: "Chatbot API Service Account"
    description: "Service account for API service operations"
    roles:
      - "roles/iam.serviceAccountUser"
      - "roles/aiplatform.admin"
      - "roles/run.admin"
      - "roles/secretmanager.secretAccessor"
    
  production_orchestrator:
    email: "nuru-ai-production@tokenhunter-457310.iam.gserviceaccount.com"
    display_name: "Nuru AI Production Service Account"
    description: "Service account for production orchestrator"
    roles:
      - "roles/iam.serviceAccountUser"
      - "roles/run.admin"
      - "roles/cloudbuild.builds.builder"
      
  telegram_bot:
    email: "tokenhunter@tokenhunter-457310.iam.gserviceaccount.com"
    display_name: "Tokenhunter"
    description: "Service account for Telegram bot operations"
    roles:
      - "roles/iam.serviceAccountUser"
      - "roles/secretmanager.secretAccessor"

  # Default compute service account (existing)
  compute_default:
    email: "867263134607-compute@developer.gserviceaccount.com"
    display_name: "Default compute service account"
    description: "Default service account for compute instances"
    managed: false  # We don't manage this one

# IAM policies for deployment prevention
iam_policies:
  prevent_hanging_builds:
    description: "Explicit IAM policy bindings to prevent deployment hanging"
    bindings:
      - role: "roles/iam.serviceAccountUser"
        members:
          - "serviceAccount:chatbot-api-sa@tokenhunter-457310.iam.gserviceaccount.com"
          - "serviceAccount:nuru-ai-production@tokenhunter-457310.iam.gserviceaccount.com"
          - "serviceAccount:tokenhunter@tokenhunter-457310.iam.gserviceaccount.com"

# Service account usage mapping
service_mapping:
  api_service: "chatbot-api-sa@tokenhunter-457310.iam.gserviceaccount.com"
  extraction_service: "nuru-ai-production@tokenhunter-457310.iam.gserviceaccount.com"
  telegram_bot_service: "tokenhunter@tokenhunter-457310.iam.gserviceaccount.com"
  
# Deployment configuration
deployment:
  default_service_account: "chatbot-api-sa@tokenhunter-457310.iam.gserviceaccount.com"
  iam_policy_application: "always"  # Always apply IAM policies during deployment
  verification: "required"  # Verify service accounts exist before deployment 