# Google Cloud Build configuration for EthCC Speakers Extraction Service
# Integrated with existing Nuru AI infrastructure
steps:
  # Build the container image using production Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/ethcc-speakers-extractor:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/ethcc-speakers-extractor:latest',
      '-f', 'Dockerfile.production',
      '.'
    ]

  # Push the container images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ethcc-speakers-extractor:$BUILD_ID']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ethcc-speakers-extractor:latest']

  # Deploy to Cloud Run in us-central1 (same region as existing services)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'ethcc-speakers-extractor',
      '--image', 'gcr.io/$PROJECT_ID/ethcc-speakers-extractor:$BUILD_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '4Gi',
      '--cpu', '2',
      '--timeout', '3600',
      '--concurrency', '1',
      '--max-instances', '3',
      '--min-instances', '0',
      '--set-env-vars', 'PYTHONPATH=/app',
      '--set-secrets', 'GOOGLE_API_KEY=google-api-key:latest',
      '--set-secrets', 'SUPABASE_URL=supabase-url:latest',
      '--set-secrets', 'SUPABASE_KEY=supabase-key:latest',
      '--tag', 'ethcc-speakers-v1'
    ]

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/ethcc-speakers-extractor:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/ethcc-speakers-extractor:latest'

# Build options optimized for production
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'
  logging: CLOUD_LOGGING_ONLY

# Build timeout
timeout: '1800s'